-- luacheck config for all yancer-* addons (WoW 3.3.5a, Lua 5.1).
-- Run with: .\tools\lint.ps1
std = "lua51"
max_line_length = false
unused_args = false

exclude_files = {
	"**/Libs/**",
	"tools/**",
}

-- Globals our addons are allowed to create.
globals = {
	"YancerBars",
	"yancerBarsDB",
	-- Blizzard tables addons add entries to
	"StaticPopupDialogs",
	"UISpecialFrames",
	"YancerChat",
	"yancerChatDB",
	"SetItemRef",
	"YancerFrames",
	"yancerFramesDB",
}

-- WoW 3.3.5a API used by our code. Add to this list as new API is used;
-- anything missing is reported as an undefined global, which catches typos.
-- Keep diagnostics.globals in .luarc.json in sync.
read_globals = {
	"LibStub",
	"CreateFrame",
	"UIParent",
	"GameTooltip",
	"wipe",
	"strtrim",
	"strsplit",
	"format",
	"tinsert",
	"tremove",
	"InCombatLockdown",
	"GetTime",
	"UnitName",
	"UnitClass",
	"hooksecurefunc",
	"RegisterStateDriver",
	"UnregisterStateDriver",
	"SecureCmdOptionParse",
	"ActionButton_ShowGrid",
	"ActionButton_HideGrid",
	"GetBindingKey",
	"RANGE_INDICATOR",
	"GetActionCooldown",
	"MainMenuBar",
	"NUM_CHAT_WINDOWS",
	"CHAT_FRAME_TEXTURES",
	"FCF_SetLocked",
	"IsShiftKeyDown",
	"IsControlKeyDown",
	"SetChatColorNameByClass",
	"SetCVar",
	"StaticPopup_Show",
	"CLOSE",
	"ChatFontNormal",
	"IsEquippedAction",
	"ClearOverrideBindings",
	"SetOverrideBindingClick",
	"MouseIsOver",
	"GetCursorInfo",
	"HasAction",
	"IsUsableAction",
	"IsActionInRange",
	"UnitExists",
	"CooldownFrame_SetTimer",
	"UnitAura",
	"DebuffTypeColor",
	"UnitCastingInfo",
	"UnitChannelInfo",
	"UnregisterUnitWatch",
	"RegisterUnitWatch",
	"PetFrame",
	"ToggleDropDownMenu",
	"UnitFrame_OnEnter",
	"UnitFrame_OnLeave",
	"UnitIsConnected",
	"UnitIsDeadOrGhost",
	"UnitIsPlayer",
	"RAID_CLASS_COLORS",
	"UnitIsTapped",
	"UnitIsTappedByPlayer",
	"FACTION_BAR_COLORS",
	"UnitReaction",
	"UnitHealth",
	"UnitHealthMax",
	"UnitIsGhost",
	"UnitIsDead",
	"PowerBarColor",
	"UnitPowerType",
	"UnitPower",
	"UnitPowerMax",
	"UnitLevel",
	"UnitClassification",
	"GetQuestDifficultyColor",
	"UnitIsVisible",
	"SetPortraitTexture",
	"UnitIsPVPFreeForAll",
	"UnitIsPVP",
	"UnitFactionGroup",
	"GetRaidTargetIndex",
	"SetRaidTargetIconTexture",
	"UnitIsPartyLeader",
	"UnitAffectingCombat",
	"IsResting",
	"GetComboPoints",
}
